# Generated by Django 4.0.5 on 2022-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos'),
        ),
    ]
